#!/bin/bash
# The logic to stop your application should be put in this script.
echo "stopping Cassandra"

CASSANDRA_PIDS=`ps -ef | grep [c]assandra | grep -v git | awk ' {print $2}'`
echo "Cassandra PID -> $CASSANDRA_PIDS"
if [ -n "$CASSANDRA_PIDS" ]; then
	echo "Killing $CASSANDRA_PIDS"
	kill -9 $CASSANDRA_PIDS > /dev/null 2>&1
fi

exit 0